name: Curl Example

on:
  push:
    branches:
      - main

jobs:
  curl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Use curl to fetch a URL
      run: curl http://127.0.0.1:54579/?key=59589a03-f760-405f-93b1-d3edd22147ed
